name: Feature Request
description: Request a feature or enchancement
title: "[RFE]: "
labels:
- enhancement
assignees:
- wranders
body:
- type: markdown
  attributes:
    value: |
      Please make sure a similar request does not already exist by looking through other open/closed issues with the `enhancement` label.
- type: textarea
  id: description
  attributes:
    label: Description
    description: "Please give a brief description of the feature/enchancement you owuld like to be added"
  validations:
    required: true
- type: textarea
  id: additional-information
  attributes:
    label: Additional Information
    description: "Please include additional details here (ie. links, screenshots, Gists, etc.)"
  validations:
    required: false
