name: Question
description: Ask away
title: "[Q]: "
labels:
- question 
assignees:
- wranders
body:
- type: textarea
  id: question
  attributes:
    label: Question
    description: What do you want to know?
  validations:
    required: true
